### ISSUE TITLE
How to disable slicing the images in strips

### ISSUE THREAD

**Issue by weihaosky** [pmonasse/disparity-with-graph-cuts#1]
Hi, in the original paper it says that to reduce the computational time, the image is sliced in multiple strips and the program is run in parallel. But the output is slightly worse. I wonder how to disable this. For now I do not care about the time-consuming and only want the best result. Thank you.

**Comment by pmonasse** [comment]
My answer is probably late, sorry I did not see the issue before...
This C++ program does not to do the slicing itself.
The IPOL demo does it through some Python code.
So running with this program on the full image you will get the best results, which are sometimes better than IPOL.
