### ISSUE TITLE
Facing -Werror=misleading-indentation and -Werror=clobbered   errors while making

### ISSUE THREAD

**Issue by gurdeepmaurya** [pmonasse/disparity-with-graph-cuts#2]
**Hi I faced following issues while making this code:**

/Graphcut/src/data.cpp: In member function ‘int Match::smoothness_penalty_gray(Coord, Coord, int) const’:
/Graphcut/src/data.cpp:180:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
     if (dl<0) dl = -dl; if (dr<0) dr = -dr;
     ^~
/Graphcut/src/data.cpp:180:25: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
     if (dl<0) dl = -dl; if (dr<0) dr = -dr;
                                 ^~
/Graphcut/src/data.cpp: In member function ‘int Match::smoothness_penalty_color(Coord, Coord, int) const’:
Graphcut/src/data.cpp:190:9: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
         if(d<0) d = -d; if (dMax<d) dMax = d;
         ^~
Graphcut/src/data.cpp:190:25: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
         if(d<0) d = -d; if (dMax<d) dMax = d;
                                 ^~
/Graphcut/src/data.cpp:192:9: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
         if(d<0) d = -d; if (dMax<d) dMax = d;
         ^~
/Graphcut/src/data.cpp:192:25: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
         if(d<0) d = -d; if (dMax<d) dMax = d;
                                 ^~
cc1plus: all warnings being treated as errors
src/CMakeFiles/KZ2.dir/build.make:62: recipe for target 'src/CMakeFiles/KZ2.dir/data.cpp.o' failed
make[2]: *** [src/CMakeFiles/KZ2.dir/data.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/KZ2.dir/all' failed
make[1]: *** [src/CMakeFiles/KZ2.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**After resolving above issues by inserting braces I got following error:**

[  9%] Building CXX object src/CMakeFiles/KZ2.dir/data.cpp.o
[ 18%] Building CXX object src/CMakeFiles/KZ2.dir/image.cpp.o
[ 27%] Building CXX object src/CMakeFiles/KZ2.dir/kz2.cpp.o
[ 36%] Building CXX object src/CMakeFiles/KZ2.dir/main.cpp.o
[ 45%] Building CXX object src/CMakeFiles/KZ2.dir/match.cpp.o
[ 54%] Building CXX object src/CMakeFiles/KZ2.dir/statistics.cpp.o
[ 63%] Building CXX object src/CMakeFiles/KZ2.dir/maxflow/graph.cpp.o
[ 72%] Building CXX object src/CMakeFiles/KZ2.dir/maxflow/maxflow.cpp.o
[ 81%] Building C object src/CMakeFiles/KZ2.dir/io_tiff.c.o
[ 90%] Building C object src/CMakeFiles/KZ2.dir/io_png.c.o
/Graphcut/src/io_png.c: In function ‘io_png_read_raw’:
/Graphcut/src/io_png.c:144:34: error: argument ‘png_transform’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
                              int png_transform, int dtype)
                                  ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
src/CMakeFiles/KZ2.dir/build.make:278: recipe for target 'src/CMakeFiles/KZ2.dir/io_png.c.o' failed
make[2]: *** [src/CMakeFiles/KZ2.dir/io_png.c.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/KZ2.dir/all' failed
make[1]: *** [src/CMakeFiles/KZ2.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by pmonasse** [comment]
Hi Akshit,
Sorry about these warnings. They are harmless but they stop the build.
To fix the problem, just remove the -Werror directives from file src/CMakeLists.txt.
I added a new commit fixing that.
Best,
Pascal Monasse

**Comment by gurdeepmaurya** [comment]
Dear Prof. Monasse,

Thanks for the quick fix. Also thanks for your your contributions in IPOL.

Regards
Akshit Maurya
