### ISSUE TITLE
Need help for fine tune 

### ISSUE THREAD

**Issue by dmilos** [pmonasse/disparity-with-graph-cuts#3]
When I try supplied samples scene_l.png and scene_r.png this produce excellent results.
What parameters to use for view2.png view1.png to produce results like disp1.png?

![view2](https://github.com/pmonasse/disparity-with-graph-cuts/assets/15868860/36e62067-72aa-4e8d-8798-77c3d44e97db)
![view1](https://github.com/pmonasse/disparity-with-graph-cuts/assets/15868860/6f0a9c4b-0547-4023-80f1-e9f579f594b5)
![disp1](https://github.com/pmonasse/disparity-with-graph-cuts/assets/15868860/eb454de2-5bcb-4f0c-9cd8-676c4d70944a)

Thanks.

**Comment by pmonasse** [comment]
There is no way you could get the perfect results you show, which are the groundtruth. You would have to tune the parameters to get the best results you can get, but there is no general rule for their optimal values.

**Comment by dmilos** [comment]
OK, thanks.
